name: Laravel CI

on:
  push:
    branches: [ main ]

jobs:
  laravel-ci:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '7.4'
    - uses: actions/checkout@v2
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: vendor/bin/phpunit

  laravel-cd:
    name: Continuous Deployment
    needs: laravel-ci
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.2.11
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-rltgoDzvO --exclude .git --exclude docker/mysql --exclude .github"
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          REMOTE_USER: ${{ secrets.SSH_USER }}
          TARGET: ${{ secrets.REMOTE_TARGET }}

      - name: Execute SSH commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.REMOTE_TARGET }}
            sudo service apache2 stop
            sudo docker-compose up -d
            sudo docker-compose exec php artisan optimize:clear
            sudo docker-compose exec php artisan down
            sudo rm -rf vendor
            sudo docker-compose exec pasquali-solution-app composer install --no-dev --no-interaction --optimize-autoloader
            sudo docker-compose exec pasquali-solution-app php artisan config:cache
            sudo docker-compose exec pasquali-solution-app php artisan route:cache
            sudo docker-compose exec pasquali-solution-app php artisan view:cache
            sudo docker-compose exec pasquali-solution-app php artisan event:cache
            sudo docker-compose exec pasquali-solution-app php artisan key:generate
            sudo docker-compose exec pasquali-solution-app php artisan jwt:secret
            sudo docker-compose exec pasquali-solution-app php artisan storage:link
            sudo docker-compose exec pasquali-solution-app php artisan optimize
            sudo docker-compose exec pasquali-solution-app php artisan migrate --force
            sudo docker-compose exec pasquali-solution-app php artisan up




